
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author KCDG
 */
public class DosyaIndirme extends javax.swing.JFrame {
    private int say=0;
    /**
     * Creates new form DosyaIndirme
     */
    public DosyaIndirme() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkProgress = new javax.swing.JProgressBar();
        jbtnDosyaIndir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ProgressBar Dosya İndirme");
        setLocation(new java.awt.Point(400, 400));

        checkProgress.setIndeterminate(true);
        checkProgress.setStringPainted(true);

        jbtnDosyaIndir.setText("Dosya İdirmeyi Baslat");
        jbtnDosyaIndir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDosyaIndirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(checkProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jbtnDosyaIndir)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(180, Short.MAX_VALUE)
                .addComponent(checkProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jbtnDosyaIndir)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnDosyaIndirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDosyaIndirActionPerformed
        // ProgressBar i ilerletmek icin bir tane timer(zamanlayiciya ihtiyacimiz var
        //Progrressbar 100 mls 1000 mls de ilerlesin diye timer nesnesinde bir obje uretecegiz.
        //timer he calistiginda islem yapacak ilk olarak null deger alacak
        Timer timer=new Timer(100,null);
        //ActionListener ile timer in calisma suresince n yapacagini belirliyoruz.
        timer.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                //Progressbar casirken yapacagi islemler
                say++;
                checkProgress.setValue(say);//sayi degiskenini progressbar a aktardik
               // System.out.println("Ne Haber!");
                if (checkProgress.getValue()==100) {
                    JOptionPane.showMessageDialog(DosyaIndirme.this, "Dosya indirme tamamlandı.");
                  //  setVisible(false); //SAdece calisan formu gizler
                    timer.stop(); //işlem tamamlandıktan sonra timer sonlandirilsin
                    SonucSayfasi sonuc=new SonucSayfasi();
                    setVisible(false); //bulundugumuz safa gizlendi
                    sonuc.setVisible(true); //sonuc sayfasi acildi
                 //   System.exit(0); //programı kapatir
                }
            }
        });
        timer.start(); //timer başlasın
    }//GEN-LAST:event_jbtnDosyaIndirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DosyaIndirme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DosyaIndirme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DosyaIndirme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DosyaIndirme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DosyaIndirme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar checkProgress;
    private javax.swing.JButton jbtnDosyaIndir;
    // End of variables declaration//GEN-END:variables
}
