
import java.util.LinkedHashSet;
import java.util.Set;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author KCDG
 */
public class RadioVeCombo extends javax.swing.JFrame {
//Ayni dil bir daha eklenmesin diye Set olusturacagiz
    Set<String> set=new LinkedHashSet<String>();
    /**
     * Creates new form RadioVeCombo
     */
    public RadioVeCombo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        rbtnJava = new javax.swing.JRadioButton();
        rbtnPython = new javax.swing.JRadioButton();
        rbtnFlutter = new javax.swing.JRadioButton();
        btnGoster = new javax.swing.JButton();
        jcmbDiller = new javax.swing.JComboBox<>();
        btnComboGoster = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RadioButton ve ComboBox Control");
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setLocationByPlatform(true);

        buttonGroup1.add(rbtnJava);
        rbtnJava.setText("Java");

        buttonGroup1.add(rbtnPython);
        rbtnPython.setText("Pyton");

        buttonGroup1.add(rbtnFlutter);
        rbtnFlutter.setText("Flutter");

        btnGoster.setText("Göster");
        btnGoster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGosterActionPerformed(evt);
            }
        });

        jcmbDiller.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Java", "Python", "Flutter", "C++", "Delphi", "C#", " " }));

        btnComboGoster.setText("Combo Goser");
        btnComboGoster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComboGosterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGoster)
                    .addComponent(rbtnFlutter)
                    .addComponent(rbtnPython)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbtnJava)
                        .addGap(77, 77, 77)
                        .addComponent(jcmbDiller, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnComboGoster)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnJava)
                    .addComponent(jcmbDiller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnComboGoster))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnPython)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnFlutter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGoster)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGosterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGosterActionPerformed
        // TODO add your handling code here:
        if (rbtnJava.isSelected()) {
            set.add("Java");
        }else{
            set.remove("Java");
        }
        if (rbtnFlutter.isSelected()) {
            set.add("Flutter");
        }else{
            set.remove("Flutter");
        } 
        if (rbtnPython.isSelected()) {
            set.add("Python");
        }else{
            set.remove("Python");
        } 
       Goster();
    }//GEN-LAST:event_btnGosterActionPerformed

    private void btnComboGosterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComboGosterActionPerformed
        // TODO add your handling code here:
        String mesaj="Şu dil secildi: "+jcmbDiller.getSelectedItem();
        JOptionPane.showMessageDialog(rootPane, mesaj);
    }//GEN-LAST:event_btnComboGosterActionPerformed
    public void Goster(){
        String mesaj="Şu Diller Seçildi : ";
        for (String dil: set) {
            mesaj+=dil + " ";
        }
        JOptionPane.showMessageDialog(rootPane, mesaj);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RadioVeCombo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RadioVeCombo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RadioVeCombo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RadioVeCombo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RadioVeCombo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComboGoster;
    private javax.swing.JButton btnGoster;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> jcmbDiller;
    private javax.swing.JRadioButton rbtnFlutter;
    private javax.swing.JRadioButton rbtnJava;
    private javax.swing.JRadioButton rbtnPython;
    // End of variables declaration//GEN-END:variables
}
